### ISSUE TITLE
OOM Error on Sift.save() calling

### ISSUE THREAD

**Issue by pkovalenko** [SiftScience/sift-android#22]
SiftScience version to 0.9.7.
On samsung S8, Samsung S7, LGMP260, I see crashes with next stacktrace
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 89987080 byte allocation with 16777216 free bytes and 52MB until OOM
       at java.lang.StringBuilder.toString(StringBuilder.java:408)
       at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:348)
       at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:98)
       at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2281)
       at siftscience.android.Queue.archive(Queue.java:164)
       at siftscience.android.Sift.save(Sift.java:352)`

Thank you

**Comment by quanpod** [comment]
Thanks for the report @pkovalenko - adding @garylee1 to investigate, although if you move to the latest version (0.9.8), we've fixed an issue that may be related.

**Comment by pkovalenko** [comment]
@quanpod We updated sift in our app to 0.9.8 and see decreases amount of crashes. But crash still reproduces.

**Comment by quanpod** [comment]
Do you have rough volume/% #'s of the crash?

**Comment by aprilodessa** [comment]
Hello @quanpod! Let me jump into this conversation. 
At this moment we have 20 users who got more than 300 such exceptions. 
Please let me know what else information can be useful to you.

**Comment by garylee1** [comment]
@aprilodessa @pkovalenko I'll look into this. Thanks for the context.

**Comment by garylee1** [comment]
we've got an upcoming fix that should address this!

**Comment by garylee1** [comment]
please hold off – we're fixing a small issue related to deserializing archived configs. the fix will be released soon with 0.9.10.

**Comment by pkovalenko** [comment]
Thank you @garylee1

**Comment by garylee1** [comment]
0.9.10 has been released – please skip over 0.9.9
