### ISSUE TITLE
Ability to turn off SDK logs

### ISSUE THREAD

**Issue by kaeawc** [SiftScience/sift-android#25]
The Sift SDK is generating quite a lot of logs at the info and debug levels, not just error. While these are good for getting started with an SDK, I really don't want to be logging this information in production apps. Would Sift be okay with me making a pull request to introduce a logging flag in the `Sift.Config.Builder`?

**Comment by garylee1** [comment]
sure, yeah! that would be great.

**Comment by garylee1** [comment]
we've addressed this with release v0.9.11

**Comment by hvisser** [comment]
This is still an issue if you either don't use ProGuard (which you should) or when you don't use ProGuard optimisation. By default Android projects do not have this turned on, and in that case debug logging will still be visible in release builds. Please add an option to the builder like many other SDKs have.
